# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Linux (x64)
      run: dotnet publish SharpCraft/SharpCraft.csproj -c Release -o Build/Linux/ --nologo -r linux-x64 --self-contained
    - name: Upload Linux (x64) Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: SharpCraft-linux-x64
        path: /home/runner/work/SharpCraft/SharpCraft/Build/Linux/
    - name: Publish Windows (x64)
      run: dotnet publish SharpCraft/SharpCraft.csproj -c Release -o Build/Windows/ --nologo -r win-x64 --self-contained
    - name: Upload Windows (x64) Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: SharpCraft-win-x64
        path: /home/runner/work/SharpCraft/SharpCraft/Build/Windows/
